import { StoreProduct } from "./types";

export const MARKETPLACE_DATA: StoreProduct[] = [
  {
    id: "mkt-1",
    name: "Arduino Uno R3 (Original)",
    description: "The classic microcontroller for all your prototyping needs. Made in Italy.",
    price: 1850.00,
    category: "Microcontrollers",
    rating: 4.9,
    image: "https://picsum.photos/400/400?random=1",
    specs: ["ATmega328P", "5V Logic", "14 Digital I/O"],
    bestVendor: "Robu.in",
    grade: 'Pro'
  },
  {
    id: "mkt-2",
    name: "Raspberry Pi 4 Model B (4GB RAM)",
    description: "Desktop-level performance for embedded projects and media centers.",
    price: 5499.00,
    category: "Computing",
    rating: 4.8,
    image: "https://picsum.photos/400/400?random=2",
    specs: ["Broadcom BCM2711", "Gigabit Ethernet", "Dual 4K Output"],
    bestVendor: "Silverline",
    grade: 'Pro'
  },
  {
    id: "mkt-3",
    name: "MG996R Metal Gear Servo",
    description: "High torque digital servo motor, perfect for robotic arms and steering.",
    price: 349.00,
    category: "Motors",
    rating: 4.5,
    image: "https://picsum.photos/400/400?random=3",
    specs: ["11kg/cm Torque", "Metal Gears", "180 Degree"],
    bestVendor: "Amazon.in",
    grade: 'Hobby'
  },
  {
    id: "mkt-4",
    name: "Industrial 24V Stepper Motor NEMA 23",
    description: "High precision motor for CNC and industrial automation.",
    price: 2450.00,
    category: "Motors",
    rating: 5.0,
    image: "https://picsum.photos/400/400?random=4",
    specs: ["2.2Nm Torque", "3A Current", "High Precision"],
    bestVendor: "Robu.in",
    grade: 'Industrial'
  },
  {
    id: "mkt-5",
    name: "Soldering Station 60W (Adjustable)",
    description: "Precision temperature controlled soldering iron for electronics.",
    price: 1299.00,
    category: "Tools",
    rating: 4.6,
    image: "https://picsum.photos/400/400?random=5",
    specs: ["200-450°C Range", "Ceramic Heater", "ESD Safe"],
    bestVendor: "Local Hub",
    grade: 'Hobby'
  },
  {
    id: "mkt-6",
    name: "Li-Po Battery 3.7V 2200mAh",
    description: "Rechargeable lithium polymer battery for portable electronics.",
    price: 450.00,
    category: "Power",
    rating: 4.8,
    image: "https://picsum.photos/400/400?random=6",
    specs: ["JST Connector", "Built-in Protection", "High Density"],
    bestVendor: "Robu.in",
    grade: 'Hobby'
  },
   {
    id: "mkt-7",
    name: "PLC Logic Controller FX3U",
    description: "Industrial Programmable Logic Controller for factory automation.",
    price: 8500.00,
    category: "Computing",
    rating: 4.9,
    image: "https://picsum.photos/400/400?random=7",
    specs: ["24V DC", "Relay Output", "Modbus RS485"],
    bestVendor: "Indiamart",
    grade: 'Industrial'
  },
  {
    id: "mkt-8",
    name: "ESP32-WROOM-32 Dev Module",
    description: "Powerful Wi-Fi + Bluetooth LE microcontroller for IoT applications.",
    price: 480.00,
    category: "Microcontrollers",
    rating: 4.7,
    image: "https://picsum.photos/400/400?random=8",
    specs: ["Dual Core", "Wi-Fi & BT", "Low Power"],
    bestVendor: "Robu.in",
    grade: 'Hobby'
  },
  {
    id: "mkt-9",
    name: "RPLIDAR A1M8 360 Degree Laser Scanner",
    description: "Low cost 2D LIDAR solution for robotic SLAM and navigation.",
    price: 8999.00,
    category: "Sensors",
    rating: 4.8,
    image: "https://picsum.photos/400/400?random=9",
    specs: ["12m Range", "360 Degree", "5.5Hz Scan Rate"],
    bestVendor: "Robu.in",
    grade: 'Pro'
  },
  {
    id: "mkt-10",
    name: "Fluke 107 Digital Multimeter",
    description: "Pocket-sized, durable digital multimeter for general troubleshooting.",
    price: 3800.00,
    category: "Tools",
    rating: 4.9,
    image: "https://picsum.photos/400/400?random=10",
    specs: ["600V AC/DC", "Resistance", "Continuity"],
    bestVendor: "Amazon.in",
    grade: 'Pro'
  },
  {
    id: "mkt-11",
    name: "MB-102 Breadboard 830 Points",
    description: "Solderless prototyping board for building and testing circuits.",
    price: 150.00,
    category: "Prototyping",
    rating: 4.5,
    image: "https://picsum.photos/400/400?random=11",
    specs: ["830 Tie Points", "Self-adhesive", "Interlocking"],
    bestVendor: "Local Hub",
    grade: 'Hobby'
  },
  {
    id: "mkt-12",
    name: "Aluminum Extrusion 2020 Profile (1m)",
    description: "Standard T-slot aluminum profile for building custom frames and CNCs.",
    price: 450.00,
    category: "Materials",
    rating: 4.8,
    image: "https://picsum.photos/400/400?random=12",
    specs: ["20mm x 20mm", "Anodized Black", "6063-T5 Alloy"],
    bestVendor: "3DPrinterStore",
    grade: 'Pro'
  },
  {
    id: "mkt-13",
    name: "PLA Filament 1.75mm Black (1kg)",
    description: "High quality PLA filament for FDM 3D printers.",
    price: 899.00,
    category: "Materials",
    rating: 4.6,
    image: "https://picsum.photos/400/400?random=13",
    specs: ["1.75mm +/-0.03", "Biodegradable", "No Bubble"],
    bestVendor: "Wol3D",
    grade: 'Hobby'
  },
  {
    id: "mkt-14",
    name: "A2212 1000KV Brushless Motor",
    description: "Standard brushless motor for quadcopters and fixed-wing aircraft.",
    price: 420.00,
    category: "Motors",
    rating: 4.4,
    image: "https://picsum.photos/400/400?random=14",
    specs: ["1000KV", "Soldered Connectors", "Mount Included"],
    bestVendor: "Robu.in",
    grade: 'Hobby'
  },
  {
    id: "mkt-15",
    name: "NVIDIA Jetson Nano Developer Kit",
    description: "Small, powerful computer for AI and robotics at the edge.",
    price: 14500.00,
    category: "Computing",
    rating: 4.9,
    image: "https://picsum.photos/400/400?random=15",
    specs: ["128-core GPU", "Quad-core CPU", "4GB RAM"],
    bestVendor: "Silverline",
    grade: 'Pro'
  },
  {
    id: "mkt-16",
    name: "DHT22 Temperature & Humidity Sensor",
    description: "Precise digital sensor for environmental monitoring.",
    price: 280.00,
    category: "Sensors",
    rating: 4.6,
    image: "https://picsum.photos/400/400?random=16",
    specs: ["-40 to 80°C", "0-100% RH", "Digital Output"],
    bestVendor: "Robu.in",
    grade: 'Hobby'
  },
  {
    id: "mkt-17",
    name: "Linear Actuator 12V 100mm Stroke",
    description: "Heavy duty electric actuator for automation and lifting.",
    price: 3200.00,
    category: "Motors",
    rating: 4.8,
    image: "https://picsum.photos/400/400?random=17",
    specs: ["100mm Stroke", "750N Force", "10mm/s Speed"],
    bestVendor: "Indiamart",
    grade: 'Industrial'
  },
  {
    id: "mkt-18",
    name: "Ultrasonic Distance Sensor HC-SR04",
    description: "Popular distance measuring module for obstacles avoidance.",
    price: 85.00,
    category: "Sensors",
    rating: 4.7,
    image: "https://picsum.photos/400/400?random=18",
    specs: ["2cm-400cm Range", "5V Operation", "15 deg Angle"],
    bestVendor: "Local Hub",
    grade: 'Hobby'
  },
  {
    id: "mkt-19",
    name: "Carbon Fiber Sheet 3mm (300x300mm)",
    description: "High-strength, lightweight rigid carbon fiber plate for drone frames.",
    price: 2100.00,
    category: "Materials",
    rating: 4.9,
    image: "https://picsum.photos/400/400?random=19",
    specs: ["3K Weave", "Matte Finish", "High Stiffness"],
    bestVendor: "Robu.in",
    grade: 'Pro'
  },
  {
    id: "mkt-20",
    name: "Digital Oscilloscope 2-Channel 100MHz",
    description: "Professional benchtop oscilloscope for signal analysis.",
    price: 18500.00,
    category: "Tools",
    rating: 4.9,
    image: "https://picsum.photos/400/400?random=20",
    specs: ["1GSa/s Sampling", "7-inch LCD", "USB storage"],
    bestVendor: "Amazon.in",
    grade: 'Industrial'
  },
  {
    id: "mkt-21",
    name: "Neodymium Magnets N52 (Pack of 10)",
    description: "Super strong rare earth magnets for clasps and sensors.",
    price: 450.00,
    category: "Materials",
    rating: 4.8,
    image: "https://picsum.photos/400/400?random=21",
    specs: ["10mm x 2mm", "Nickel Plated", "Axial Magnetization"],
    bestVendor: "Local Hub",
    grade: 'Hobby'
  },
  {
    id: "mkt-22",
    name: "USB Logic Analyzer 8 Channel",
    description: "Debug digital circuits and protocols like I2C, SPI, and UART.",
    price: 650.00,
    category: "Tools",
    rating: 4.5,
    image: "https://picsum.photos/400/400?random=22",
    specs: ["24MHz Sampling", "Saleae Compatible", "Test Hooks Incl."],
    bestVendor: "Robu.in",
    grade: 'Pro'
  },
  {
    id: "mkt-23",
    name: "Arctic Silver 5 Thermal Paste",
    description: "High performance thermal compound for heatsinks and CPUs.",
    price: 850.00,
    category: "Materials",
    rating: 5.0,
    image: "https://picsum.photos/400/400?random=23",
    specs: ["3.5g Syringe", "99.9% Silver", "Non-conductive"],
    bestVendor: "Amazon.in",
    grade: 'Pro'
  }
];